# .slather.yml
coverage_service: cobertura_xml
xcodeproj: doc-bot.xcodeproj
scheme: doc-bot
configuration: Debug
source_directory: ./doc-bot
binary_basename: doc-bot
build_directory: ./build
output_directory: .
ignore:
  - "doc-botTests/*"
  - "doc-botUITests/*"
  - "build/*"
  - "LlamaCpp/*"
  - "Pods/*"
  - "**/*Tests*"
  - "**/*Test*"